CREATE TABLE ExtendedEvents.SQLMonitoring_CompletedQueries
    (
         SQLMonitoring_CompletedQueriesID       
        ,timestamp                     
        ,name                          
        ,attach_activity_id            
        ,actual_row_count              
        ,batch_text                    
        ,attach_activity_id_xfer       
        ,client_hostname               
        ,client_app_name               
        ,compile_time                  
        ,collect_system_time           
        ,cpu_time                      
        ,convert_issue                 
        ,dop                           
        ,database_name                 
        ,expression                    
        ,duration                      
        ,last_row_count                
        ,granted_memory_kb             
        ,logical_reads                 
        ,line_number                   
        ,offset_end                    
        ,offset                        
        ,optimizer_timeout_task_number 
        ,opcode                        
        ,physical_reads                
        ,parameterized_plan_handle     
        ,query_hash                    
        ,plan_handle                   
        ,query_plan_hash               
        ,query_operation_node_id       
        ,result                        
        ,request_id                    
        ,session_id                    
        ,row_count                     
        ,sort_warning_type             
        ,signal_duration               
        ,statement                     
        ,sql_text                      
        ,thread_id                     
        ,task_time                     
        ,unmatched_database_name       
        ,timeout_type                  
        ,unmatched_schema_name         
        ,unmatched_index_name          
        ,used_memory_kb                
        ,unmatched_table_name          
        ,wait_resource                 
        ,username                      
        ,worktable_physical_reads      
        ,wait_type                     
        ,writes                        
        ,worktable_physical_writes     
    )